import string

TT_IDENTIFIER = "TT_IDENTIFIER"
TT_KEYWORD = "TT_KEYWORD"
TT_EQ = "TT_EQ"

TT_FLOAT = 'TT_FLOAT'
TT_INT = 'TT_INT'

TT_PLUS = 'TT_PLUS'
TT_MINUS = 'TT_MINUS'
TT_MUL = 'TT_MUL'
TT_DIV = 'TT_DIV'

TT_LPAREN = 'TT_LPAREN'
TT_RPAREN = 'TT_RPAREN'

TT_EOF = 'TT_EOF'

DIGITS = '0123456789'
LETTERS = string.ascii_letters
LETTERS_DIGITS = LETTERS + DIGITS

KEYWORDS = ['VAR']
